name: MFE CI

on:
  push:
    branches:
      - ci-cd-learning

  pull_request:
    branches:
      - ci-cd-learning

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Shell
        run: npx ng build shell

      - name: Build Login MFE
        run: npx ng build mfe-login  