name: MFE CI

on:
  push:
    branches:
      - ci-cd-learning

  pull_request:
    branches:
      - ci-cd-learning

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
    fail-fast: false
      matrix:
        app:
          - shell
          - mfe-login
          - mfe-admin
          - mfe-user
          - mfe-product
          - mfe-order

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      # - name: Test ${{ matrix.app }}
      #   run: npx ng test ${{ matrix.app }} --watch=false --no-progress

      - name: Build ${{ matrix.app }}
        run: npx ng build ${{ matrix.app }}